---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kv-secrets
  labels:
    app: minio-kv
data:
  MINIO_ACCESS_KEY: NTExZThkNmM4NGVlNjVmZWRhMzRlZmRjYzUzNjYyODFhMjJiNmRmZAo= # base64 encoded
  MINIO_SECRET_KEY: ZDg4YjQ4MTZhYzExZjBlZTVlZmNjNTI4MmQyZmU5ODk2MTYyYTFkNgo= # base64 encoded